import type { Metadata } from 'next'
import '@/styles/globals.css'
import { QueryClientProvider } from '@tanstack/react-query'
import reactQueryClient from '@/configs/react-query-config'
import { QuestionProvider } from '@/context/QuestionContext'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body>
        <QueryClientProvider client={reactQueryClient}>
          <QuestionProvider>{children}</QuestionProvider>
        </QueryClientProvider>
      </body>
    </html>
  )
}
